### ISSUE TITLE
execution error

### ISSUE THREAD

**Issue by steph-cha51** [oPromessa/flickr-uploader#41]
Hi, what can i do for this error please?
Steph.

```
[1306][2018.03.03 12:44:42]:[7204       ][PRINT   ]:[uploadr] --------- (V2.6.8) Start time: 2018.03.03 12:44:42 ---------
[1306][2018.03.03 12:44:42]:[7204       ][PRINT   ]:[uploadr] FILES_DIR: [/volume1/photo/test_dan]
[1306][2018.03.03 12:44:43]:[7204       ][PRINT   ]:[uploadr] Setting up database:[flickrdb]
[1306][2018.03.03 12:44:43]:[7204       ][PRINT   ]:[uploadr] Database version: [3]
[1306][2018.03.03 12:44:43]:[7204       ][PRINT   ]:[uploadr] Completed database setup
[1306][2018.03.03 12:44:43]:[7204       ][PRINT   ]:[uploadr] Checking if token is available... if not will authenticate
[1306][2018.03.03 12:44:43]:[7204       ][PRINT   ]:[uploadr] *****Removing empty Sets from DB*****
[1306][2018.03.03 12:44:43]:[7204       ][PRINT   ]:[uploadr] *****Completed removing empty Sets from DB*****
[1306][2018.03.03 12:44:43]:[7204       ][PRINT   ]:[uploadr] *****Adding Flickr Sets to DB*****
Traceback (most recent call last):
  File "uploadr.py", line 4544, in <module>
    flick.getFlickrSets()
  File "uploadr.py", line 3288, in getFlickrSets
    logging.info(xml.etree.ElementTree.tostring(
AttributeError: 'module' object has no attribute 'etree'

```

**Comment by oPromessa** [comment]
If you can edit file uploadr.py and find and follow these instructions:

import xml
# CODING: For some systems this second import is required. To confirm.
# Seems to avoid problem
# logging.info(xml.etree.ElementTree.tostring(
# AttributeError: 'module' object has no attribute 'etree'
# import xml.etree.ElementTree

Let me know if it works. oPromessa

**Comment by steph-cha51** [comment]
cool ;) it's works !
