### ISSUE TITLE
UnboundLocalError: local variable 'con' referenced before assignment

### ISSUE THREAD

**Issue by hefistion** [oPromessa/flickr-uploader#53]
After uploading the files the script is interrupted with the following error message,

and do not create the sets

```
[1728][2018.04.15 16:23:43]:[8096       ][PRINT   ]:[uploadr]   5943 of         5943 files processed (uploaded, md5ed or timestamp checked).
Traceback (most recent call last):
  File "./uploadr.py", line 4688, in <module>
    flick.upload()
  File "./uploadr.py", line 1025, in upload
    if con is not None:
UnboundLocalError: local variable 'con' referenced before assignment
carlos@raspberrypi:~/flickr-uploader-master $
```

The same with the option --dryrun

Python 2.7.13

**Comment by oPromessa** [comment]
Hi there @hefistion , sorry for that.

I think I did fix this issue on version [2.7.6](https://github.com/oPromessa/flickr-uploader/tree/2.7.6) which I've just released.

Let me know if it works!

Thanks, oPromessa

**Comment by hefistion** [comment]
With the latest version 2.7.6 the error is corrected

thank you very much
```
  Initial Found Files:[  5936]
          - Bad Files:[     0] = [  5936]
                 Note: some Bad files may no longer exist!
Photos count:
                Local:[  5936]
               Flickr:[  8426]
Not in sets on Flickr:[  2368]
[1849][2018.04.16 16:27:50]:[13972      ][PRINT   ]:[uploadr] --------- (V2.7.6) End time: 2018.04.16 16:27:50 -----------(Log:40)
--------- End:  ---------
carlos@raspberrypi:~/flickr-uploader-2.7.6 $

```

**Comment by oPromessa** [comment]
Great. Check out [V2.7.7](https://github.com/oPromessa/flickr-uploader/releases/tag/2.7.7) recently release.
