### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by jamborta** [oPromessa/flickr-uploader#66]
I get the following error (using the code from master):

`[2417][2018.05.10 06:28:39]:[MainProcess][ERROR   ]:[root] (<class 'requests.exceptions.ConnectionError'>, ConnectionError(ProtocolError('Connection aborted.', error("(104, 'ECONNRE
SET')",)),), <traceback object at 0x7fb425574cf8>)
[2417][2018.05.10 06:28:39]:[5380       ][PRINT   ]:[uploadr] (<class 'requests.exceptions.ConnectionError'>, ConnectionError(ProtocolError('Connection aborted.', error("(104, 'ECON
NRESET')",)),), <traceback object at 0x7fb425574cf8>)
[2417][2018.05.10 06:28:39]:[MainProcess][ERROR   ]:[root] Sleep 10 and check if file is already uploaded
[2417][2018.05.10 06:28:39]:[5380       ][PRINT   ]:[uploadr] Sleep 10 and check if file is already uploaded
[2417][2018.05.10 06:28:49]:[5380       ][PRINT   ]:[uploadr]     Reuploading:[/samba/secured_disk2/photos/2017-08-Aug/Hrvatska/2017-08-03_17-36-09-img_4645.jpg] [2/10 attempts].
[2417][2018.05.10 06:36:32]:[MainProcess][ERROR   ]:[root] +++#038: Caught IOError, HTTP exception
[2417][2018.05.10 06:36:32]:[5380       ][PRINT   ]:[uploadr] +++#038: Caught IOError, HTTP exception
[2417][2018.05.10 06:36:32]:[MainProcess][ERROR   ]:[root] (<class 'requests.exceptions.ConnectionError'>, ConnectionError(ProtocolError('Connection aborted.', error("(104, 'ECONNRE
SET')",)),), <traceback object at 0x7fb42573e320>)
[2417][2018.05.10 06:36:32]:[5380       ][PRINT   ]:[uploadr] (<class 'requests.exceptions.ConnectionError'>, ConnectionError(ProtocolError('Connection aborted.', error("(104, 'ECON
NRESET')",)),), <traceback object at 0x7fb42573e320>)
[2417][2018.05.10 06:36:32]:[MainProcess][ERROR   ]:[root] Sleep 10 and check if file is already uploaded
[2417][2018.05.10 06:36:32]:[5380       ][PRINT   ]:[uploadr] Sleep 10 and check if file is already uploaded
Traceback (most recent call last):
  File "./uploadr.py", line 525, in <module>
    run_uploadr(PARSED_ARGS)
  File "./uploadr.py", line 352, in run_uploadr
    FLICK.upload()
  File "/home/tamas/apps/flickr-uploader/lib/FlickrUploadr.py", line 602, in upload
    success = self.uploadFile(lock=None, file=file)
  File "/home/tamas/apps/flickr-uploader/lib/FlickrUploadr.py", line 1366, in uploadFile
    setName)
  File "/home/tamas/apps/flickr-uploader/lib/FlickrUploadr.py", line 3199, in is_already_uploaded
    .find('photos').attrib['total'])
ValueError: invalid literal for int() with base 10: ''`

**Comment by oPromessa** [comment]
Hi there

From what I could gather something went extremely wrong on the connection with Flickr and the protections I have around it did fail... really weird!

Can you please re-run it with a bit more debug... and send me the error report again.  

### More debug...
- Please edit *uploadr.ini* file and at the end, change LOGGING_LEVEL to 10 which is for uploadr.py to provide DEBUG  messages.
`LOGGING_LEVEL = 10`
- To remove change it back to the previous value: 40 (for ERROR and CRITICAL messages only).
`LOGGING_LEVEL = 40`

Thanks,

oPromessa

**Comment by oPromessa** [comment]
Hi again,

1. One note, As I mentioned on occasions Flickr does not provide back reliable results when ACTIVITY/REQUESTS are very high during a certain period of time... which may justify this issue! Don't know if this is the case... 
   - [ ] To confirm: you can go to [Flickr-Settings-Sharing](https://www.flickr.com/account/sharing)...
   - [ ] Select "Your API keys" (at the end of the information screen)
   - [ ] And you can read the number of call sin the last 24 hours. On my case I have: `95,576 calls in the last 24 hours`
   - [ ] Then select "Stats" to get some more graphical information. Too many "reds" it's a sign of over-usage!

2. In particular, this may happen on the **first** load. and may not occur on subsequent loads...

3. Anyhow I've added a bit more protection for this issue on the code on branch [fix-may18-issue16](https://github.com/oPromessa/flickr-uploader/tree/fix-may18-issue66) should you want to test it. Again, set LOGGING_LEVEL to Debug and send me your feedback.

Thanks, oPromessa.

**Comment by oPromessa** [comment]
Hi there, did you have any more issues?

Meanwhile I now noticed I failed earlier to confirm the changes on branch [fix-may18-issue16](https://github.com/oPromessa/flickr-uploader/tree/fix-may18-issue66) that I had previously mentioned. I'm sorry for that.

They arena available.

Thanks, oPromessa

**Comment by jamborta** [comment]
@oPromessa, thanks. I'll update and run again.
